DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS DROIT;
DROP TABLE IF EXISTS PRODUITSCOMMANDES;
DROP TABLE IF EXISTS COMMANDES;
DROP TABLE IF EXISTS PRODUITS;
DROP TABLE IF EXISTS SEMAINE;
DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS TYPEPRIX;
DROP TABLE IF EXISTS ORIGINE;
DROP TABLE IF EXISTS CATEGORIE;


CREATE TABLE CATEGORIE(

	idCategorie INT NOT NULL,
	nomCategorie VARCHAR(20),
	PRIMARY KEY(idCategorie)
);

CREATE TABLE ORIGINE(

	idOrigine INT NOT NULL,
	description VARCHAR(30),
	PRIMARY KEY(idOrigine)
);

CREATE TABLE TYPEPRIX(

	idTypePrix INT NOT NULL,
	designation VARCHAR(20),
	PRIMARY KEY(idTypePrix)
);

CREATE TABLE LIEU(

	idLieu INT NOT NULL,
	nomLieu VARCHAR(20),
	PRIMARY KEY(idLieu)
);

CREATE TABLE SEMAINE(

	idSemaine INT NOT NULL,
	dateDebut date,
	dateFin date,
	valide BOOLEAN,
	PRIMARY KEY(idSemaine)
);

CREATE TABLE PRODUITS(

	idProduit INT NOT NULL AUTO_INCREMENT,
	designation VARCHAR(20),
	commentaire TEXT,
	prix FLOAT,
	idTypePrix INT NOT NULL,
	codeProduit INT,
	idOrigine INT NOT NULL,
	disponible BOOLEAN,
	idCategorie INT NOT NULL,
	PRIMARY KEY(idProduit),
	FOREIGN KEY(idCategorie) REFERENCES CATEGORIE(idCategorie),
	FOREIGN KEY(idOrigine) REFERENCES ORIGINE(idOrigine),
	FOREIGN KEY(idTypePrix) REFERENCES TYPEPRIX(idTypePrix)

);

CREATE TABLE COMMANDES(
	
	idCommande INT NOT NULL AUTO_INCREMENT,
	dateCommande DATE,
	idSemaine INT NOT NULL,
	prixTotal FLOAT,
	idLieu INT NOT NULL,
	PRIMARY KEY(idCommande),
	FOREIGN KEY(idLieu) REFERENCES LIEU(idLieu),
	FOREIGN KEY(idSemaine) REFERENCES SEMAINE(idSemaine)
);

CREATE TABLE PRODUITSCOMMANDES(

	idProduit INT NOT NULL,
	idCommande INT NOT NULL,
	quantite FLOAT,
	prix FLOAT,
	idTypePrix INT NOT NULL,
	FOREIGN KEY(idProduit) REFERENCES PRODUITS(idProduit),
	FOREIGN KEY(idCommande) REFERENCES COMMANDES(idCommande),
	FOREIGN KEY(idTypePrix) REFERENCES TYPEPRIX(idTypePrix)	
);

CREATE TABLE DROIT(

	idDroit INT NOT NULL,
	PRIMARY KEY(idDroit)
);

CREATE TABLE UTILISATEUR(

	idUser INT NOT NULL AUTO_INCREMENT,
	nom VARCHAR(20),
	mdp VARCHAR(30),
	email VARCHAR(30),
	idDroit INT NOT NULL,
	PRIMARY KEY(idUser),
	FOREIGN KEY(idDroit) REFERENCES DROIT(idDroit)
);

