DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS PRODUITSCOMMANDES;
DROP TABLE IF EXISTS COMMANDES;
DROP TABLE IF EXISTS PRODUITS;
DROP TABLE IF EXISTS SEMAINE;
DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS TYPEPRIX;
DROP TABLE IF EXISTS ORIGINE;
DROP TABLE IF EXISTS CATEGORIE;


CREATE TABLE CATEGORIE(

	idCategorie INT NULL AUTO_INCREMENT,
	nomCategorie VARCHAR(20),
	PRIMARY KEY(idCategorie)
);

CREATE TABLE ORIGINE(

	idOrigine INT NULL AUTO_INCREMENT,
	description VARCHAR(30),
	PRIMARY KEY(idOrigine)
);

CREATE TABLE TYPEPRIX(

	idTypePrix INT NULL AUTO_INCREMENT,
	designation VARCHAR(20),
	PRIMARY KEY(idTypePrix)
);

CREATE TABLE LIEU(

	idLieu INT NULL AUTO_INCREMENT,
	nomLieu VARCHAR(20),
	PRIMARY KEY(idLieu)
);

CREATE TABLE SEMAINE(

	idSemaine INT NULL AUTO_INCREMENT,
	dateDebut date,
	dateFin date,
	valide BOOLEAN,
	PRIMARY KEY(idSemaine)
);

CREATE TABLE PRODUITS(

	idProduit INT NULL AUTO_INCREMENT,
	designation VARCHAR(20),
	commentaire TEXT,
	prix FLOAT,
	idTypePrix INT NULL,
	codeProduit INT,
	idOrigine INT NULL,
	disponible BOOLEAN,
	idCategorie INT NULL,
	PRIMARY KEY(idProduit),
	FOREIGN KEY(idCategorie) REFERENCES CATEGORIE(idCategorie),
	FOREIGN KEY(idOrigine) REFERENCES ORIGINE(idOrigine),
	FOREIGN KEY(idTypePrix) REFERENCES TYPEPRIX(idTypePrix)

);

CREATE TABLE COMMANDES(
	
	idCommande INT NULL AUTO_INCREMENT,
	dateCommande DATE,
	idSemaine INT NULL,
	prixTotal FLOAT,
	idLieu INT NULL,
	PRIMARY KEY(idCommande),
	FOREIGN KEY(idLieu) REFERENCES LIEU(idLieu),
	FOREIGN KEY(idSemaine) REFERENCES SEMAINE(idSemaine)
);

CREATE TABLE PRODUITSCOMMANDES(

	idProduit INT NULL,
	idCommande INT NULL,
	quantite FLOAT,
	prix FLOAT,
	idTypePrix INT NULL,
	FOREIGN KEY(idProduit) REFERENCES PRODUITS(idProduit),
	FOREIGN KEY(idCommande) REFERENCES COMMANDES(idCommande),
	FOREIGN KEY(idTypePrix) REFERENCES TYPEPRIX(idTypePrix)	
);

CREATE TABLE UTILISATEUR(

	idUser INT NULL AUTO_INCREMENT,
	nom VARCHAR(20),
	mdp VARCHAR(30),
	email VARCHAR(30),
	idDroit INT NULL,
	droitCommande boolean,
	PRIMARY KEY(idUser)
);

INSERT INTO CATEGORIE VALUES('',"Legume");
INSERT INTO CATEGORIE VALUES('',"Fruit");

INSERT INTO ORIGINE VALUES('',"FRANCE");
INSERT INTO ORIGINE VALUES('',"ESPAGNE");
INSERT INTO ORIGINE VALUES('',"MAROC");

INSERT INTO TYPEPRIX VALUES('',"Piece");
INSERT INTO TYPEPRIX VALUES('',"Kg");
INSERT INTO TYPEPRIX VALUES('',"Piece/Kg");

INSERT INTO LIEU VALUES('',"Belfort Nord");
INSERT INTO LIEU VALUES('',"Marché des Vosges");

INSERT INTO PRODUITS VALUES('',"Patate","Elles sont bonnes mes patates ",0.78,1,100,1,0,1);
INSERT INTO PRODUITS VALUES('',"Tomate","",5.78,2,101,2,1,1);
INSERT INTO PRODUITS VALUES('',"Banane","",2,3,101,2,1,2);

INSERT INTO UTILISATEUR VALUES('',"maxime","a","adresse@mail.com",1,false);
INSERT INTO UTILISATEUR VALUES('',"nicolas","a","adresse@mail.com",2,true);

INSERT INTO SEMAINE VALUES('', '12-02-2014', '19-02-2014', 1);
INSERT INTO SEMAINE VALUES('', '24-02-2014', '02-03-2014', 1);

INSERT INTO COMMANDES VALUES('', '13-02-2014', 1, 15.2, 1);